### ISSUE TITLE
Quote inside admonition

### ISSUE THREAD

**Issue by minh-trancong** [javalent/admonitions#226]
I am having a problem with quote inside admonition in Live Preview mode. It renders abundant spaces 😢

Editing:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/92774562/159130212-53d95fac-d638-4106-9cc8-165e80e152e8.png">

Reading:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/92774562/159130230-635d54ec-6184-43d1-bd3d-2e9da3c4e7a7.png">

but in **Live Preview**:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/92774562/159130248-2297488c-bb38-4909-afe6-fba977981f8f.png">

How can I fix this problem? Thank you!☺️

**Comment by sigrunixia** [comment]
The inconsistency between Live Preview and Reading mode is due to the different rendering processes which govern those two. There is some CSS snippets out there to attempt to fix it for things like headers and paragraphs, but it's quite like fighting a losing battle.

Additionally, depending on the theme you are using, there can be styling on top of that. 

The specific selector for block quotes within admonitions on live preview is:

`body > div.app-container > div.horizontal-main-container > div > div.workspace-split.mod-vertical.mod-root > div > div.workspace-tab-container > div > div > div.view-content > div.markdown-source-view.cm-s-obsidian.mod-cm6.is-folding.is-live-preview.node-insert-event > div > div.cm-scroller > div.cm-sizer > div.cm-contentContainer > div > div.cm-preview-code-block.cm-embed-block.markdown-rendered.admonition-parent.admonition-info-parent > div.callout.admonition.admonition-info.admonition-plugin.is-collapsible > div.callout-content.admonition-content > blockquote`

Give or take a few divs. You would target a css snippet with `.is-live-preview.admonition-content {` for any admonition content (body) styling, and `.is-live-preview .admonition-content blockquote {`for blockquote styling. For spacing, you are typically looking at altering the `margin` and `padding` properties.

Admonitions now comes with this by default which should solve the issue you were experiencing. If not, then specifically targeting as mentioned above will take care of the rest. 

```css
.is-live-preview .admonition-content>* {
    margin-top: 0;
    margin-bottom: 0;
}
```
