### ISSUE TITLE
[Feature request] Add the possibility to automatically add tags to blocks

### ISSUE THREAD

**Issue by ultrapoci** [javalent/admonitions#241]
It would be quite useful if it was possible to automatically add a user defined tag to each custom admonition block. I don't think this should be visible: the plugin could simply add a comment above or below each block: `%%#tag%%`. This is what I already do manually, for example.

**Comment by sigrunixia** [comment]
@ultrapoci What would be the use case for adding a tag to the block automatically?

**Comment by valentine195** [comment]
This is out of the scope of the plugin.

**Comment by sigrunixia** [comment]
> > 
> 
> I used custom block to highlight questions in my thesis I order to keep a reminder to answer them later. Since not every document has a question that needs answering, a tag is a good way to have a nice list of every document that has the "question" block.

This would be better handled by having a plugin such as [templater](https://github.com/SilentVoid13/Templater) insert your custom blocks. 

I imagine your issue comes from live preview around a code block which is inconsistent with how it displays markdown comments?

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/68425372/234319469-d061ffc0-ed17-49a2-b7fa-763385cf54df.png">

Might I suggest storing the tags inside the admonition? Search can detect the tags inside the code block, and markdown comments also work within it.
