### ISSUE TITLE
multi-column callout snippet does not work with alternate styling of admonition plugin 

### ISSUE THREAD

**Issue by mmfs37** [javalent/admonitions#243]
This is a snippet that allowes to use finally multiple columns like notion or other platforms.  Looks amazing for dashboards etc

How it should look:
![image](https://user-images.githubusercontent.com/100991030/163716168-fcb422e4-6672-42bf-8fe8-b3f0bf5c2f82.png)

However I am a fan of alternative styling and I want to preserve that for my other callouts. So if I activate that it looks like this.
![image](https://user-images.githubusercontent.com/100991030/163716203-88d5a40a-853c-4eab-8c42-3839fd07fbc6.png)

I do know that this happens, and I had multiple custom snippets and its very easy to solve. Its usually solvable by adding it to the admonition callout registry
![image](https://user-images.githubusercontent.com/100991030/163716232-09a8deb7-d11c-403d-b29d-1021dc5d1695.png)

-> now it does  work
![image](https://user-images.githubusercontent.com/100991030/163716428-bf0a25e6-6ed0-409a-bde1-c614b34ef5b0.png)

**however** as soon as I restart obsidian it completly stops working. It gets invisible. I can't do anything. I can confirm it is still there but it in live preview and reading mode it shows nothing. How can that be? Before the restart everythign was perfect. Now it stops....
![image](https://user-images.githubusercontent.com/100991030/163716415-c07de486-b8ef-473b-aeb8-355e7565bf74.png)

https://github.com/efemkay/obsidian-modular-css-layout/blob/main/MCL%20Multi%20Column.css <- this is the snippet

That s the example code I used for the screenshots:

> [!multi-column]
> 
>> [!subtle]+ Work
>> your notes or lists here. using markdown formatting
>
>> [!advip-subtle]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!subtle]+ Charity
>> your notes or lists here. using markdown formatting

**Comment by sigrunixia** [comment]
Tested this and its working as intended as far as styling.

Admonitions created callouts inherit their styling from their admonition settings. To fix how the callout styling looks while maintaining the admonition's looks, custom css would be needed to target the `.callout[data-callout="name"] and additional `.admonition-parent-name` css. 

As for why multi-column turns invisible when registered, is due to competing css and styles. The snippet is trying to do one thing (which is fully loaded), and the plugin trying to force the other (which happens upon reload). It results in something that cannot be rendered as it's a mess. 

This is not something we'll really be able to fix on the plugin end. We can provide examples over time in our documentation (I have added this to my todo), on how to stylise callouts and admonitions differently, and increase more inter-snippet support with callout versions.
